# Generated by Django 5.2.1 on 2025-07-29 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stockexit_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='api.account'),
        ),
    ]
