# Generated by Django 5.2.1 on 2025-07-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_username_and_more'),
    ]

    operations = [
        # Opération pour supprimer la contrainte unique sur username héritée d'AbstractUser
        migrations.RunSQL(
            "CREATE UNIQUE INDEX temp_unique_username ON api_user (username) WHERE id = -1;",  # Index temporaire impossible
            reverse_sql="DROP INDEX IF EXISTS temp_unique_username;",
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS api_user_username_key;",  # Supprimer l'index unique s'il existe
            reverse_sql="CREATE UNIQUE INDEX api_user_username_key ON api_user (username);",
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS api_user_username;",  # Supprimer l'autre index possible
            reverse_sql="CREATE UNIQUE INDEX api_user_username ON api_user (username);",
        ),
    ]
