# Generated by Django 5.2.1 on 2025-07-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_username'),
        ('api', '0003_auto_20250725_1808'),
    ]

    operations = [
    ]
