# Generated by Django 5.2.1 on 2025-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_date_joined_remove_user_email_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Store',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_per_store',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_global',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='store',
            new_name='store',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('store', 'username'), name='unique_username_per_store'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', True)), fields=('username',), name='unique_username_global'),
        ),
    ]
