# Generated by Django 5.2.1 on 2025-08-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer_debt_stockexit_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexit',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='stockexit',
            name='exit_type',
            field=models.CharField(choices=[('sale', 'Vente'), ('transfer', 'Transfert inter-entrepôts')], default='sale', max_length=10),
        ),
    ]
