# Generated by Django 5.2.1 on 2025-08-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_transfer_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockexit',
            name='destination_warehouse',
        ),
        migrations.RemoveField(
            model_name='stockexit',
            name='exit_type',
        ),
    ]
