# Generated by Django 5.2.1 on 2025-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_stock_transfer_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Achat (Entrée Stock)'), ('sale', 'Vente (Sortie Stock)'), ('service', 'Apport (Prestation de service)'), ('expense', 'Dépense (Frais divers)'), ('transfer', 'Transfert entre comptes'), ('adjustment', 'Ajustement')], max_length=20),
        ),
    ]
