# Generated by Django 5.2.1 on 2025-08-03 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_financialtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='api.customer'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Achat (Entrée Stock)'), ('sale', 'Vente (Sortie Stock)'), ('service', 'Apport (Prestation de service)'), ('expense', 'Dépense (Frais divers)'), ('debt_payment', 'Remboursement de dette'), ('transfer', 'Transfert entre comptes'), ('adjustment', 'Ajustement')], max_length=20),
        ),
    ]
